import type { Therapist } from "../types";

export const mockTherapistsList: Therapist[] = [
  {
    id: "1",
    slug: "dr-priya-sharma",
    name: "Dr. Priya Sharma",
    qualification: "Ph.D. Clinical Psychology",
    professionalTitle: "Clinical Psychologist",
    bio: "Specializing in evidence-based therapies for anxiety and mood disorders with over a decade of clinical experience.",
    yearsExperience: 12,
    languages: ["English", "Hindi"],
    specializations: ["Anxiety", "Depression", "Stress"],
    rating: 4.9,
    totalReviews: 142,
    sessionFee: 1500,
    consultationMode: "online",
    gender: "female",
    verified: true,
    availableToday: true,
    nextAvailableSlot: "Today, 3:00 PM",
  },
  {
    id: "2",
    slug: "dr-arjun-mehta",
    name: "Dr. Arjun Mehta",
    qualification: "M.D. Psychiatry",
    professionalTitle: "Psychiatrist",
    bio: "Experienced psychiatrist helping individuals and couples navigate life transitions and relationship challenges.",
    yearsExperience: 8,
    languages: ["English", "Hindi", "Gujarati"],
    specializations: ["Relationships", "Family", "Career"],
    rating: 4.8,
    totalReviews: 98,
    sessionFee: 2000,
    consultationMode: "both",
    gender: "male",
    verified: true,
    availableToday: true,
    nextAvailableSlot: "Today, 5:30 PM",
  },
  {
    id: "3",
    slug: "dr-kavitha-nair",
    name: "Dr. Kavitha Nair",
    qualification: "M.Phil. Clinical Psychology",
    professionalTitle: "Child & Adolescent Psychologist",
    bio: "Dedicated to supporting young minds through academic pressure, social challenges, and developmental concerns.",
    yearsExperience: 10,
    languages: ["English", "Malayalam", "Tamil"],
    specializations: ["Child & Teen", "Anxiety", "ADHD"],
    rating: 4.9,
    totalReviews: 87,
    sessionFee: 1200,
    consultationMode: "online",
    gender: "female",
    verified: true,
    availableToday: false,
    nextAvailableSlot: "Tomorrow, 10:00 AM",
  },
  {
    id: "4",
    slug: "dr-rohit-kapoor",
    name: "Dr. Rohit Kapoor",
    qualification: "Ph.D. Counseling Psychology",
    professionalTitle: "Addiction Counselor",
    bio: "Helping individuals recover from substance use and behavioral addictions through compassionate, structured therapy.",
    yearsExperience: 15,
    languages: ["English", "Hindi", "Punjabi"],
    specializations: ["Addiction", "Stress", "Trauma"],
    rating: 4.7,
    totalReviews: 63,
    sessionFee: 1800,
    consultationMode: "both",
    gender: "male",
    verified: true,
    availableToday: true,
    nextAvailableSlot: "Today, 4:00 PM",
  },
  {
    id: "5",
    slug: "dr-meera-reddy",
    name: "Dr. Meera Reddy",
    qualification: "M.A. Counseling Psychology",
    professionalTitle: "Counseling Psychologist",
    bio: "Focused on helping women navigate life transitions, self-esteem issues, and workplace challenges.",
    yearsExperience: 6,
    languages: ["English", "Telugu", "Hindi"],
    specializations: ["Stress", "Career", "Self-Esteem"],
    rating: 4.8,
    totalReviews: 54,
    sessionFee: 1000,
    consultationMode: "online",
    gender: "female",
    verified: true,
    availableToday: true,
    nextAvailableSlot: "Today, 6:00 PM",
  },
  {
    id: "6",
    slug: "dr-sameer-khan",
    name: "Dr. Sameer Khan",
    qualification: "M.D. Psychiatry",
    professionalTitle: "Psychiatrist",
    bio: "Providing medication management and psychotherapy for severe anxiety, OCD, and mood disorders.",
    yearsExperience: 11,
    languages: ["English", "Hindi", "Urdu"],
    specializations: ["OCD", "Anxiety", "Depression"],
    rating: 4.6,
    totalReviews: 76,
    sessionFee: 2200,
    consultationMode: "both",
    gender: "male",
    verified: true,
    availableToday: false,
    nextAvailableSlot: "Tomorrow, 11:00 AM",
  },
  {
    id: "7",
    slug: "dr-anita-desai",
    name: "Dr. Anita Desai",
    qualification: "Ph.D. Clinical Psychology",
    professionalTitle: "Couples Therapist",
    bio: "Expert in relationship counseling, communication patterns, and rebuilding trust between partners.",
    yearsExperience: 14,
    languages: ["English", "Hindi", "Marathi"],
    specializations: ["Relationships", "Family", "Grief"],
    rating: 4.9,
    totalReviews: 118,
    sessionFee: 1800,
    consultationMode: "online",
    gender: "female",
    verified: true,
    availableToday: true,
    nextAvailableSlot: "Today, 2:00 PM",
  },
  {
    id: "8",
    slug: "dr-vikram-singh",
    name: "Dr. Vikram Singh",
    qualification: "M.Phil. Psychiatric Social Work",
    professionalTitle: "Clinical Social Worker",
    bio: "Community-focused mental health professional specializing in trauma recovery and family systems therapy.",
    yearsExperience: 9,
    languages: ["English", "Hindi", "Punjabi"],
    specializations: ["Trauma", "Family", "Depression"],
    rating: 4.7,
    totalReviews: 45,
    sessionFee: 1300,
    consultationMode: "online",
    gender: "male",
    verified: true,
    availableToday: false,
    nextAvailableSlot: "Tomorrow, 9:00 AM",
  },
  {
    id: "9",
    slug: "dr-lakshmi-iyer",
    name: "Dr. Lakshmi Iyer",
    qualification: "M.Phil. Clinical Psychology",
    professionalTitle: "Clinical Psychologist",
    bio: "Providing CBT and mindfulness-based interventions for anxiety, insomnia, and emotional regulation difficulties.",
    yearsExperience: 7,
    languages: ["English", "Tamil", "Kannada"],
    specializations: ["Anxiety", "Insomnia", "Stress"],
    rating: 4.8,
    totalReviews: 62,
    sessionFee: 1400,
    consultationMode: "online",
    gender: "female",
    verified: true,
    availableToday: true,
    nextAvailableSlot: "Today, 7:00 PM",
  },
  {
    id: "10",
    slug: "dr-aditya-joshi",
    name: "Dr. Aditya Joshi",
    qualification: "M.D. Psychiatry",
    professionalTitle: "Psychiatrist",
    bio: "Specializing in ADHD, bipolar disorder, and medication-assisted treatments for complex cases.",
    yearsExperience: 13,
    languages: ["English", "Hindi", "Bengali"],
    specializations: ["ADHD", "Bipolar", "Depression"],
    rating: 4.6,
    totalReviews: 89,
    sessionFee: 2500,
    consultationMode: "both",
    gender: "male",
    verified: true,
    availableToday: false,
    nextAvailableSlot: "Tomorrow, 2:30 PM",
  },
  {
    id: "11",
    slug: "dr-pooja-gupta",
    name: "Dr. Pooja Gupta",
    qualification: "M.A. Clinical Psychology",
    professionalTitle: "Counseling Psychologist",
    bio: "Warm and empathetic approach to therapy focused on body image, eating concerns, and self-compassion.",
    yearsExperience: 5,
    languages: ["English", "Hindi"],
    specializations: ["Self-Esteem", "Eating Disorders", "Stress"],
    rating: 4.9,
    totalReviews: 38,
    sessionFee: 900,
    consultationMode: "online",
    gender: "female",
    verified: true,
    availableToday: true,
    nextAvailableSlot: "Today, 8:00 PM",
  },
  {
    id: "12",
    slug: "dr-rajesh-menon",
    name: "Dr. Rajesh Menon",
    qualification: "Ph.D. Clinical Neuropsychology",
    professionalTitle: "Neuropsychologist",
    bio: "Expert in cognitive assessments, brain-behavior relationships, and rehabilitation after neurological events.",
    yearsExperience: 18,
    languages: ["English", "Malayalam", "Hindi"],
    specializations: ["Cognitive Issues", "Trauma", "ADHD"],
    rating: 4.7,
    totalReviews: 71,
    sessionFee: 2800,
    consultationMode: "offline",
    gender: "male",
    verified: true,
    availableToday: false,
    nextAvailableSlot: "Wed, 10:00 AM",
  },
];

export const filterOptions = {
  specializations: [
    "Anxiety", "Depression", "Stress", "Relationships", "Family",
    "Career", "Addiction", "Trauma", "ADHD", "OCD", "Child & Teen",
    "Self-Esteem", "Grief", "Insomnia",
  ],
  languages: [
    "English", "Hindi", "Tamil", "Telugu", "Malayalam",
    "Kannada", "Bengali", "Marathi", "Gujarati", "Punjabi", "Urdu",
  ],
  experience: ["1-3 years", "3-5 years", "5-10 years", "10+ years"],
  gender: ["Male", "Female", "Other"],
  consultationMode: ["Online", "In-Person", "Both"],
  fee: ["Under ₹1000", "₹1000-₹1500", "₹1500-₹2000", "₹2000+"],
  rating: ["4.5+", "4.0+", "3.5+"],
  availability: ["Available Today", "Available Tomorrow"],
} as const;
